DTOO_FIND_LIBRARY_EXT(
  "CGNS_FOUND" "cgnslib.h" "libcgns.so" 
  "CGNS_INCLUDE_DIR" "CGNS_LINK_DIRECTORY" "CGNS_LIBRARIES" 
  "CGNS_FIND_COMPONENTS"
  "${DTOO_EXTERNLIBS}/cgns/include" "${DTOO_EXTERNLIBS}/cgns/lib"
)