# -*- cmake -*-

# - Find Google perftools
# Find the Google perftools includes and libraries
# This module defines
# GOOGLEPERFTOOLS_INCLUDE_DIR, where to find heap-profiler.h, etc.
# GOOGLEPERFTOOLS_FOUND, If false, do not try to use Google perftools.
# also defined for general use are
# TCMALLOC_LIBRARIES, where to find the tcmalloc library.
# STACKTRACE_LIBRARIES, where to find the stacktrace library.
# PROFILER_LIBRARIES, where to find the profiler library.

IF(GOOGLEPERFTOOLS_INCLUDE_DIR AND GOOGLEPERFTOOLS_PROFILER_LIBRARY AND GOOGLEPERFTOOLS_TCMALLOC_LIBRARY)
  SET(GOOGLEPERFTOOLS_FOUND "YES")
ELSE(GOOGLEPERFTOOLS_INCLUDE_DIR AND GOOGLEPERFTOOLS_PROFILER_LIBRARY AND GOOGLEPERFTOOLS_TCMALLOC_LIBRARY)
  FIND_PATH(GOOGLEPERFTOOLS_INCLUDE_DIR google/heap-profiler.h
  /usr/local/include
  /usr/include
  )

  FIND_LIBRARY(GOOGLEPERFTOOLS_TCMALLOC_LIBRARY
  NAMES tcmalloc
  PATHS /usr/lib64 /usr/lib /usr/local/lib
  )

  FIND_LIBRARY(GOOGLEPERFTOOLS_PROFILER_LIBRARY
  NAMES profiler
  PATHS /usr/lib64 /usr/lib /usr/local/lib
  )

  IF (GOOGLEPERFTOOLS_TCMALLOC_LIBRARY AND GOOGLEPERFTOOLS_PROFILER_LIBRARY AND GOOGLEPERFTOOLS_INCLUDE_DIR)
  SET(GOOGLEPERFTOOLS_FOUND "YES")
  ELSE (GOOGLEPERFTOOLS_TCMALLOC_LIBRARY AND GOOGLEPERFTOOLS_PROFILER_LIBRARY AND GOOGLEPERFTOOLS_INCLUDE_DIR)
  SET(GOOGLEPERFTOOLS_FOUND "NO")
  ENDIF (GOOGLEPERFTOOLS_TCMALLOC_LIBRARY AND GOOGLEPERFTOOLS_PROFILER_LIBRARY AND GOOGLEPERFTOOLS_INCLUDE_DIR)

  IF (GOOGLEPERFTOOLS_FOUND)
  MESSAGE(STATUS "Found Google perftools")
  ELSE (GOOGLEPERFTOOLS_FOUND)
  IF (GOOGLE_PERFTOOLS_FIND_REQUIRED)
  MESSAGE(FATAL_ERROR "Could not find Google perftools library")
  ENDIF (GOOGLE_PERFTOOLS_FIND_REQUIRED)
  ENDIF (GOOGLEPERFTOOLS_FOUND)

  MARK_AS_ADVANCED(
  GOOGLEPERFTOOLS_TCMALLOC_LIBRARY
  GOOGLEPERFTOOLS_PROFILER_LIBRARY
  GOOGLEPERFTOOLS_INCLUDE_DIR
  )
ENDIF(GOOGLEPERFTOOLS_INCLUDE_DIR AND GOOGLEPERFTOOLS_PROFILER_LIBRARY AND GOOGLEPERFTOOLS_TCMALLOC_LIBRARY)