SET(CGAL_DEFINITIONS -frounding-math)
#
# prevents error assertion violation
#
ADD_DEFINITIONS(-DCGAL_DISABLE_ROUNDING_MATH_CHECK)

DTOO_FIND_LIBRARY_HEADERONLY_EXT(
  "CGAL_FOUND" "CGAL" 
  "CGAL_INCLUDE_DIR" ""
)
