  # - Find LASSO
# Find the LASSO includes and client library
# This module defines
# LASSO_DEFINITIONS: compiler flags for compiling with LASSO
# LASSO_INCLUDE_DIR: where to find LASSO.h
# LASSO_LIBRARIES: the libraries needed to use LASSO
# LASSO_FOUND: if false, do not try to use LASSO
#SET(LASSO_INCLUDE_DIR "not found")
#SET(LASSO_LIBRARIES "not found")

#SET(LASSO_DEFINITIONS "-liGeom")
IF(LASSO_INCLUDE_DIR AND LASSO_LIBRARIES AND LASSO_LINK_DIRECTORY)
  SET(LASSO_FOUND TRUE)
ELSE(LASSO_INCLUDE_DIR AND LASSO_LIBRARIES AND LASSO_LINK_DIRECTORY)
  FIND_PATH(LASSO_INCLUDE_DIR iRel.h
  ${DTOO_EXTERNLIBS}/lasso/include/
  )
  FIND_LIBRARY(LASSO_LIBRARIES NAMES iRel
  PATHS
  ${DTOO_EXTERNLIBS}/lasso/lib
  ${DTOO_EXTERNLIBS}/lasso/lib64
  )

 FIND_PATH(LASSO_LINK_DIRECTORY libiRel.so
    ${DTOO_EXTERNLIBS}/ALL/lib
    $ENV{DTOO_ROOTDIR}/lib
  )

  IF(LASSO_INCLUDE_DIR AND LASSO_LIBRARIES AND LASSO_LINK_DIRECTORY)
    SET(LASSO_FOUND TRUE)
    MESSAGE(STATUS "Found LASSO: ${LASSO_INCLUDE_DIR}, ${LASSO_LIBRARIES}, ${LASSO_LINK_DIRECTORY}")
  ELSE(LASSO_INCLUDE_DIR AND LASSO_LIBRARIES AND LASSO_LINK_DIRECTORY)
    SET(LASSO_FOUND FALSE)
    MESSAGE(STATUS "LASSO not found.")
  ENDIF(LASSO_INCLUDE_DIR AND LASSO_LIBRARIES AND LASSO_LINK_DIRECTORY)

  MARK_AS_ADVANCED(LASSO_INCLUDE_DIR LASSO_LIBRARIES LASSO_LINK_DIRECTORY)
ENDIF(LASSO_INCLUDE_DIR AND LASSO_LIBRARIES AND LASSO_LINK_DIRECTORY)