# - Find CGNS
# Find the CGNS includes and client library
# This module defines
# CGNS_DEFINITIONS: compiler flags for compiling with CGNS
# CGNS_INCLUDE_DIR: where to find CGNS.h
# CGNS_LIBRARIES: the libraries needed to use CGNS
# CGNS_FOUND: if false, do not try to use CGNS
#SET(CGNS_INCLUDE_DIR "not found")
#SET(CGNS_LIBRARIES "not found")

SET(CGNS_DEFINITIONS "")
IF(CGNS_INCLUDE_DIR AND CGNS_LIBRARIES AND CGNS_LINK_DIRECTORY)
  SET(CGNS_FOUND TRUE)
ELSE(CGNS_INCLUDE_DIR AND CGNS_LIBRARIES AND CGNS_LINK_DIRECTORY)
  FIND_PATH(CGNS_INCLUDE_DIR cgnslib.h
  ${DTOO_EXTERNLIBS}/cgns/include/
  )
  FIND_LIBRARY(CGNS_LIBRARIES NAMES cgns libcgns
  PATHS
  ${DTOO_EXTERNLIBS}/cgns/lib
  ${DTOO_EXTERNLIBS}/cgns/lib64
  )

 FIND_PATH(CGNS_LINK_DIRECTORY libcgns.so
    ${DTOO_EXTERNLIBS}/ALL/lib
    $ENV{DTOO_ROOTDIR}/lib
  )

  IF(CGNS_INCLUDE_DIR AND CGNS_LIBRARIES AND CGNS_LINK_DIRECTORY)
    SET(CGNS_FOUND TRUE)
    MESSAGE(STATUS "Found CGNS: ${CGNS_INCLUDE_DIR}, ${CGNS_LIBRARIES}, ${CGNS_LINK_DIRECTORY}")
  ELSE(CGNS_INCLUDE_DIR AND CGNS_LIBRARIES AND CGNS_LINK_DIRECTORY)
    SET(CGNS_FOUND FALSE)
    MESSAGE(STATUS "CGNS not found.")
  ENDIF(CGNS_INCLUDE_DIR AND CGNS_LIBRARIES AND CGNS_LINK_DIRECTORY)

  MARK_AS_ADVANCED(CGNS_INCLUDE_DIR CGNS_LIBRARIES CGNS_LINK_DIRECTORY)
ENDIF(CGNS_INCLUDE_DIR AND CGNS_LIBRARIES AND CGNS_LINK_DIRECTORY)