SET(CGAL_DEFINITIONS -frounding-math)
#
# prevents error assertion violation
#
ADD_DEFINITIONS(-DCGAL_DISABLE_ROUNDING_MATH_CHECK)

DTOO_FIND_LIBRARY(
  "CGAL_FOUND" "CGAL" "libCGAL.so" 
  "CGAL_INCLUDE_DIR" "CGAL_LINK_DIRECTORY" "CGAL_LIBRARIES" 
  "CGAL_FIND_COMPONENTS"
)