MACRO(USE_CGAL)
  SET(CGAL_FIND_REQUIRED FALSE) 
  FIND_PACKAGE(CGAL)
  IF ((NOT CGAL_FOUND))
    USING_MESSAGE("Skipping because of missing CGAL")
    RETURN()
  ENDIF((NOT CGAL_FOUND))
  IF(NOT CGAL_USED AND CGAL_FOUND)
    SET(CGAL_USED TRUE)
    INCLUDE_DIRECTORIES(${CGAL_INCLUDE_DIR})
    SET(EXTRA_LIBS ${EXTRA_LIBS} ${CGAL_LIBRARIES})
    #
    # prevents error assertion violation
    #
    ADD_DEFINITIONS(-DCGAL_DISABLE_ROUNDING_MATH_CHECK)
  ENDIF()
ENDMACRO(USE_CGAL)
